import 'package:intl/intl.dart';
import 'package:collection/collection.dart';
import '../../../../core/providers/mock_database.dart';
import '../../../../core/utils/sip_calculator.dart';
import '../entities/calendar_event.dart';

class CalendarEngine {
  /// Compiles all calendar events (manual and auto-generated) for a given date range.
  static List<CalendarEvent> compileAllEvents({
    required MockDatabaseState dbState,
    required DateTime startRange,
    required DateTime endRange,
  }) {
    final List<CalendarEvent> compiled = [];
    final start = DateTime(startRange.year, startRange.month, startRange.day);
    final end = DateTime(endRange.year, endRange.month, endRange.day, 23, 59, 59);

    // 1. SIP Events (Auto-generated)
    for (final sip in dbState.sips) {
      if (sip.isActive != 1 || sip.deletedAt != null) continue;
      final investment = dbState.investments.firstWhereOrNull((i) => i.id == sip.investmentId);
      if (investment == null || investment.deletedAt != null || investment.isArchived == 1) continue;

      final scheduledDates = SipCalculator.calculateScheduledDates(
        startDate: sip.startDate,
        frequency: sip.frequency,
        sipDate: sip.sipDate,
        startLimit: start,
        endLimit: end,
        endDate: sip.endDate,
      );

      for (final date in scheduledDates) {
        compiled.add(CalendarEvent(
          id: 'sip_${sip.id}_${DateFormat('yyyyMMdd').format(date)}',
          title: 'SIP Due: ${investment.name}',
          amount: sip.amount,
          category: 'Investment',
          date: date,
          isAutoGenerated: true,
          sourceId: sip.id,
          sourceType: 'sip',
          status: 'Pending',
          priority: 'Medium',
          createdAt: sip.createdAt,
          updatedAt: sip.updatedAt,
        ));
      }
    }

    // 2. Personal Loans / EMIs & Receivables (from people table)
    for (final p in dbState.people) {
      if (p.deletedAt != null || p.isArchived == 1 || p.dueDate == null) continue;
      
      final dueDate = p.dueDate!;
      if (dueDate.isBefore(start) || dueDate.isAfter(end)) continue;

      final receivableBal = dbState.getPersonReceivableBalance(p.id);
      final liabilityBal = dbState.getPersonLiabilityBalance(p.id);

      if (receivableBal > 0) {
        compiled.add(CalendarEvent(
          id: 'receivable_${p.id}',
          title: 'Follow Up Receivable: ${p.name}',
          amount: receivableBal,
          category: 'Receivables',
          date: dueDate,
          isAutoGenerated: true,
          sourceId: p.id,
          sourceType: 'receivable',
          status: 'Pending',
          priority: 'Medium',
          createdAt: p.createdAt,
          updatedAt: p.updatedAt,
        ));
      }

      if (liabilityBal > 0) {
        // If it's a liability, it's a Loan Payment or EMI due date.
        compiled.add(CalendarEvent(
          id: 'liability_${p.id}',
          title: 'Loan/EMI Due: ${p.name}',
          amount: liabilityBal,
          category: 'Liability',
          date: dueDate,
          isAutoGenerated: true,
          sourceId: p.id,
          sourceType: 'liability',
          status: 'Pending',
          priority: 'High',
          createdAt: p.createdAt,
          updatedAt: p.updatedAt,
        ));
      }
    }

    // 3. Expected Income Events
    for (final ei in dbState.expectedIncomes) {
      if (ei.deletedAt != null || ei.expectedDate == null || ei.status != 'pending') continue;
      
      final expectedDate = ei.expectedDate!;
      if (expectedDate.isBefore(start) || expectedDate.isAfter(end)) continue;

      compiled.add(CalendarEvent(
        id: 'expected_income_${ei.id}',
        title: 'Expected Income: ${ei.source}',
        amount: ei.amount,
        category: 'Income',
        date: expectedDate,
        isAutoGenerated: true,
        sourceId: ei.id,
        sourceType: 'expected_income',
        status: 'Pending',
        priority: 'Medium',
        createdAt: ei.createdAt,
        updatedAt: ei.updatedAt,
      ));
    }

    // 4. Goal Target Dates
    for (final g in dbState.goals) {
      if (g.deletedAt != null || g.isArchived == 1 || g.deadline == null) continue;
      
      final deadline = g.deadline!;
      if (deadline.isBefore(start) || deadline.isAfter(end)) continue;

      final remaining = g.targetAmount - g.currentAmount;
      if (remaining <= 0) continue; // Already achieved

      compiled.add(CalendarEvent(
        id: 'goal_${g.id}',
        title: 'Goal Target: ${g.name}',
        amount: remaining,
        category: 'Goals',
        date: deadline,
        isAutoGenerated: true,
        sourceId: g.id,
        sourceType: 'goal',
        status: 'Pending',
        priority: 'Medium',
        createdAt: g.createdAt,
        updatedAt: g.updatedAt,
      ));
    }

    // 5. IPO Pool Events (Open, Close, Listing)
    for (final pool in dbState.ipoPools) {
      if (pool.deletedAt != null) continue;

      if (pool.openDate != null) {
        final d = pool.openDate!;
        if (d.isAfter(start) && d.isBefore(end)) {
          compiled.add(CalendarEvent(
            id: 'ipo_open_${pool.id}',
            title: 'IPO Open: ${pool.name}',
            amount: pool.applicationCost * (pool.contributors.length + pool.soloApplications),
            category: 'IPO',
            date: d,
            isAutoGenerated: true,
            sourceId: pool.id,
            sourceType: 'ipo_pool',
            status: 'Pending',
            priority: 'Medium',
            createdAt: pool.createdAt,
            updatedAt: pool.createdAt,
          ));
        }
      }

      if (pool.closeDate != null) {
        final d = pool.closeDate!;
        if (d.isAfter(start) && d.isBefore(end)) {
          compiled.add(CalendarEvent(
            id: 'ipo_close_${pool.id}',
            title: 'IPO Close: ${pool.name}',
            amount: pool.applicationCost * (pool.contributors.length + pool.soloApplications),
            category: 'IPO',
            date: d,
            isAutoGenerated: true,
            sourceId: pool.id,
            sourceType: 'ipo_pool',
            status: 'Pending',
            priority: 'Medium',
            createdAt: pool.createdAt,
            updatedAt: pool.createdAt,
          ));
        }
      }

      if (pool.listingDate != null) {
        final d = pool.listingDate!;
        if (d.isAfter(start) && d.isBefore(end)) {
          compiled.add(CalendarEvent(
            id: 'ipo_listing_${pool.id}',
            title: 'IPO Listing: ${pool.name}',
            amount: pool.applicationCost * (pool.contributors.length + pool.soloApplications),
            category: 'IPO',
            date: d,
            isAutoGenerated: true,
            sourceId: pool.id,
            sourceType: 'ipo_pool',
            status: 'Pending',
            priority: 'Medium',
            createdAt: pool.createdAt,
            updatedAt: pool.createdAt,
          ));
        }
      }
    }

    // 6. MTF Interest Billing Dates
    for (final pos in dbState.mtfPositions) {
      if (pos.deletedAt != null || pos.isClosed == 1) continue;

      // MTF Billing is monthly, starting from pos.interestStartDate.
      // Find all monthly billing dates between start and end.
      DateTime currentBilling = pos.interestStartDate;
      // Advance to start range month if needed
      while (currentBilling.isBefore(start)) {
        currentBilling = DateTime(currentBilling.year, currentBilling.month + 1, currentBilling.day);
      }

      int loops = 0;
      while ((currentBilling.isBefore(end) || currentBilling.isAtSameMomentAs(end)) && loops < 100) {
        loops++;
        final monthlyInterest = (pos.borrowedCapital * (pos.interestRate / 100)) / 12;
        compiled.add(CalendarEvent(
          id: 'mtf_${pos.id}_${currentBilling.year}${currentBilling.month}',
          title: 'MTF Interest: ${pos.instrument} (${pos.broker})',
          amount: monthlyInterest,
          category: 'Liability',
          date: currentBilling,
          isAutoGenerated: true,
          sourceId: pos.id,
          sourceType: 'mtf_position',
          status: 'Pending',
          priority: 'Medium',
          createdAt: pos.createdAt,
          updatedAt: pos.updatedAt,
        ));
        currentBilling = DateTime(currentBilling.year, currentBilling.month + 1, currentBilling.day);
      }
    }

    // 7. Manual Events
    for (final e in dbState.calendarEvents) {
      if (e.deletedAt != null) continue;
      if (e.date.isBefore(start) || e.date.isAfter(end)) continue;
      compiled.add(e);
    }

    // Sort by date
    compiled.sort((a, b) => a.date.compareTo(b.date));
    return compiled;
  }

  /// Calculates calendar insights for a given date range.
  static CalendarInsights calculateInsights(List<CalendarEvent> events) {
    double income = 0.0;
    double outflow = 0.0;

    for (final e in events) {
      if (e.status == 'Cancelled') continue;
      if (e.category == 'Income') {
        income += e.amount;
      } else {
        outflow += e.amount;
      }
    }

    return CalendarInsights(
      expectedIncome: income,
      expectedOutflow: outflow,
      netCashFlow: income - outflow,
    );
  }

  /// Performs financial load analysis, finding the busiest days.
  static List<LoadAnalysisDay> calculateLoadAnalysis(List<CalendarEvent> events) {
    // Group outflow events by date (ignoring time)
    final Map<String, List<CalendarEvent>> grouped = {};
    for (final e in events) {
      if (e.status == 'Cancelled') continue;
      if (e.category == 'Income') continue; // only outflow is counted for financial obligation load

      final key = DateFormat('yyyy-MM-dd').format(e.date);
      grouped.putIfAbsent(key, () => []).add(e);
    }

    final List<LoadAnalysisDay> list = [];
    grouped.forEach((dateStr, dayEvents) {
      final date = DateTime.parse(dateStr);
      final totalOutflow = dayEvents.fold<double>(0.0, (sum, e) => sum + e.amount);
      list.add(LoadAnalysisDay(
        date: date,
        totalOutflow: totalOutflow,
        events: dayEvents,
      ));
    });

    // Sort descending by total outflow
    list.sort((a, b) => b.totalOutflow.compareTo(a.totalOutflow));
    return list;
  }
}

class CalendarInsights {
  final double expectedIncome;
  final double expectedOutflow;
  final double netCashFlow;

  CalendarInsights({
    required this.expectedIncome,
    required this.expectedOutflow,
    required this.netCashFlow,
  });
}

class LoadAnalysisDay {
  final DateTime date;
  final double totalOutflow;
  final List<CalendarEvent> events;

  LoadAnalysisDay({
    required this.date,
    required this.totalOutflow,
    required this.events,
  });
}
