class CalendarEvent {
  final String id;
  final String title;
  final double amount;
  final String category; // 'Income' | 'Investment' | 'Liability' | 'Receivables' | 'Goals' | 'IPO' | 'Subscription' | 'Insurance' | 'Manual'
  final DateTime date;
  final String? time;
  final String status; // 'Pending' | 'Completed' | 'Cancelled'
  final String? notes;
  final String priority; // 'Low' | 'Medium' | 'High'
  final bool isAutoGenerated;
  final String? sourceId;
  final String? sourceType; // 'sip' | 'goal' | 'receivable' | 'expected_income' | 'mtf_position' | 'ipo_pool'
  final bool isRecurring;
  final String? recurrenceInterval; // 'daily' | 'weekly' | 'monthly' | 'yearly'
  final DateTime createdAt;
  final DateTime updatedAt;
  final DateTime? deletedAt;

  CalendarEvent({
    required this.id,
    required this.title,
    required this.amount,
    required this.category,
    required this.date,
    this.time,
    this.status = 'Pending',
    this.notes,
    this.priority = 'Medium',
    this.isAutoGenerated = false,
    this.sourceId,
    this.sourceType,
    this.isRecurring = false,
    this.recurrenceInterval,
    required this.createdAt,
    required this.updatedAt,
    this.deletedAt,
  });

  CalendarEvent copyWith({
    String? id,
    String? title,
    double? amount,
    String? category,
    DateTime? date,
    String? Function()? time,
    String? status,
    String? Function()? notes,
    String? priority,
    bool? isAutoGenerated,
    String? Function()? sourceId,
    String? Function()? sourceType,
    bool? isRecurring,
    String? Function()? recurrenceInterval,
    DateTime? createdAt,
    DateTime? updatedAt,
    DateTime? Function()? deletedAt,
  }) {
    return CalendarEvent(
      id: id ?? this.id,
      title: title ?? this.title,
      amount: amount ?? this.amount,
      category: category ?? this.category,
      date: date ?? this.date,
      time: time != null ? time() : this.time,
      status: status ?? this.status,
      notes: notes != null ? notes() : this.notes,
      priority: priority ?? this.priority,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      sourceId: sourceId != null ? sourceId() : this.sourceId,
      sourceType: sourceType != null ? sourceType() : this.sourceType,
      isRecurring: isRecurring ?? this.isRecurring,
      recurrenceInterval: recurrenceInterval != null ? recurrenceInterval() : this.recurrenceInterval,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      deletedAt: deletedAt != null ? deletedAt() : this.deletedAt,
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'title': title,
      'amount': amount,
      'category': category,
      'date': date.toIso8601String(),
      'time': time,
      'status': status,
      'notes': notes,
      'priority': priority,
      'isAutoGenerated': isAutoGenerated,
      'sourceId': sourceId,
      'sourceType': sourceType,
      'isRecurring': isRecurring,
      'recurrenceInterval': recurrenceInterval,
      'createdAt': createdAt.toIso8601String(),
      'updatedAt': updatedAt.toIso8601String(),
      'deletedAt': deletedAt?.toIso8601String(),
    };
  }

  factory CalendarEvent.fromJson(Map<String, dynamic> json) {
    return CalendarEvent(
      id: json['id'] as String,
      title: json['title'] as String,
      amount: (json['amount'] as num).toDouble(),
      category: json['category'] as String,
      date: DateTime.parse(json['date'] as String),
      time: json['time'] as String?,
      status: json['status'] as String? ?? 'Pending',
      notes: json['notes'] as String?,
      priority: json['priority'] as String? ?? 'Medium',
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      sourceId: json['sourceId'] as String?,
      sourceType: json['sourceType'] as String?,
      isRecurring: json['isRecurring'] as bool? ?? false,
      recurrenceInterval: json['recurrenceInterval'] as String?,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      deletedAt: json['deletedAt'] != null ? DateTime.parse(json['deletedAt'] as String) : null,
    );
  }
}
